[package]
name = "kloenk"
version = "0.1.0"
authors = ["Jelmer Alphenaar <https://hatsu.tech>"]
edition = "2021"
repository = "https://github.com/Jelmerta/Kloenk/"
description = "Custom Rust engine targeting WASM with WebGpu (with the dream of creating a multiplayer online game)"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"
winit = "0.29" # 0.30 exists but has breaking changes
env_logger = "0.10"
log = "0.4"
wgpu = "22.1.0"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }
cgmath = "0.18"
gltf = "1.4.1"
anyhow = "1.0.89"
itertools = "0.9.0"
glyphon = "0.6.0"
fs_extra = "1.2"
glob = "0.3"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[build-dependencies]
anyhow = "1.0.89"
fs_extra = "1.2"
glob = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0"
wgpu = { version = "22.1.0", features = ["webgl"] }
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = { version = "0.3.70", features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }
reqwest = { version = "0.11" }
getrandom = { version = "0.2", features = ["js"] }

[[bin]]
name = "kloenk_bin"
path = "src/main.rs"

[profile.release]
opt-level = "z"
panic = "abort"
lto = true
strip = true
