[package]
name = "kloenk"
version = "0.1.0"
authors = ["Ben Hansen <https://github.com/sotrh>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"
winit = { version = "0.29", features = ["rwh_05"]}
env_logger = "0.10"
log = "0.4"
wgpu = "22.1"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }
cgmath = "0.18"
gltf = "1.4.1"
anyhow = "1.0"
itertools = "0.9.0"

# We can probably remove this part if we don't load in images
[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "22.0", features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }
reqwest = { version = "0.11" }
getrandom = { version = "0.2", features = ["js"] }

[[bin]]
name = "kloenk_bin"
path = "src/main.rs"
#cfg = "web_sys_unstable_apis" #Hm, probably only required for web...

[profile.release]
opt-level = "z"
panic = "abort"
lto = true

# TODO Make sure this is only used when releasing and not during development
[build]
release = true
# [package.metadata.trunk]
# files = ["resources"]

#[package]
#name = "kloenk"
#version = "0.1.0"
#authors = ["Jelmer Alphenaar <https://github.com/jelmerta>"]
#edition = "2021"
#license = "GPL-3.0-or-later"
#description = "Some game"
#repository = "https://github.com/Jelmerta/Kloenk"
#
#[lib]
#crate-type = ["cdylib", "rlib"]
#
#[[bin]]
#name = "kloenk"
#path = "src/main.rs"
#
#[dependencies]
#cfg-if = "1.0.0"
#winit = { version = "0.29.4", features = ["rwh_05"] } # https://www.reddit.com/r/rust/comments/1856u5a/what_is_the_state_of_winit_x_wgpu/ We downgrade to raw-window-handle 0.5 such that wgpu works correctly. WGPU does not have 0.6 yet.
#env_logger = "0.10.1"
#log = "0.4.20"
#wgpu = "0.18.0"
#pollster = "0.3.0"
#
#[target.'cfg(target_arch = "wasm32")'.dependencies]
#console_error_panic_hook = "0.1.6"
#console_log = "1.0"
#wgpu = { version = "0.18", features = ["webgl"]} # Probably won't need webgl as we are trying to use WebGPU
#wasm-bindgen = "=0.2.89"
#wasm-bindgen-futures = "0.4.39"
#web-sys = { version = "0.3.64", features = [
#    "Document",
#    "Window",
#    "Element",
#]}
