name: deploy-infra
run-name: Deploying infra
on:
  push:
    branches: [ "main" ]
    paths: [ 'kloenk-infra/**', '.github/workflows/deploy-infra.yaml' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx to help out with building docker image (
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./kloenk-infra
          push: 'true'
          tags: hydrogax/kloenk-infra:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.0

      - name: Retrieve new container and run on server using remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ARTIFACT_HOST }}
          username: ${{ secrets.ARTIFACT_USERNAME }}
          key: ${{ secrets.ARTIFACT_SSH_KEY }}
          script:
            docker pull hydrogax/kloenk-infra && (docker rm -f kloenk-infra || true) && docker run -d --mount type=volume,src=kloenk-static,dst=/usr/share/nginx/html:ro --mount type=volume,src=/etc/ssl-kloenk,dst=/etc/ssl:ro --mount type=volume,src=/var/www/certbot-acme,dst=/var/www/certbot-acme -p 80:80 -p 443:443 --name kloenk-infra hydrogax/kloenk-infra