name: deploy-server
run-name: Deploying server
on:
  push:
    branches: [ "main" ]
    paths: [ 'kloenk-server/**', '.github/workflows/deploy-server.yaml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.0
#
#      - name: Set up Docker Buildx to help out with building docker image (
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Build and push Docker images
#        uses: docker/build-push-action@v6
#        with:
#          context: ./kloenk-client
#          push: 'true'
#          tags: hydrogax/kloenk:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout project
#        uses: actions/checkout@v4.2.0
#
#      - name: Retrieve new container and run on server using remote ssh commands
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.ARTIFACT_HOST }}
#          username: ${{ secrets.ARTIFACT_USERNAME }}
#          key: ${{ secrets.ARTIFACT_SSH_KEY }}
#          script: docker pull hydrogax/kloenk && (docker rm -f kloenk || true) && docker run -d -v /etc/ssl-kloenk:/etc/ssl:ro -v /var/www/certbot-acme:/var/www/certbot-acme -p 80:80 -p 443:443 --name kloenk hydrogax/kloenk