name: deploy-to-web
run-name: Deploying client
on:
  push:
    branches: [ "main" ]
    paths: [ 'kloenk-client/**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx to help out with building docker image (
        uses: docker/setup-buildx-action@v3

      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./kloenk-client
          push: false
          tags: hydrogax/kloenk-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Move client outside container
        run: docker create --name kloenk-client hydrogax/kloenk-client && docker cp kloenk-client:/app/output/ /kloenk-client/html/ && docker cp kloenk-client:/app/output/ /kloenk-client/html/assets/

        #        COPY --from=builder /app/output /usr/share/nginx/html
        #COPY assets /usr/share/nginx/html/assets

        #      - name: Retrieve new container and run on server using remote ssh commands
        #        uses: appleboy/ssh-action@v1.0.3
        #        uses: appleboy/scp-action@v1
        #        with:
        #          host: ${{ secrets.ARTIFACT_HOST }}
        #          username: ${{ secrets.ARTIFACT_USERNAME }}
        #  key: ${{ secrets.ARTIFACT_SSH_KEY }}
      #          script: docker create --name kloenk-client hydrogax/kloenk-client && docker cp kloenk-client:/app/output/ /usr/share/nginx/html && docker cp kloenk-client:/app/output/ /usr/share/nginx/html/assets/

      - name: Copy client + assets to server using remote ssh commands
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.ARTIFACT_HOST }}
          username: ${{ secrets.ARTIFACT_USERNAME }}
          key: ${{ secrets.ARTIFACT_SSH_KEY }}
          source: "kloenk-client/html/*"
          target: "/usr/share/nginx/html/"

  #      - name: Copy assets to server using remote ssh commands
  #        uses: appleboy/scp-action@v1
  #        with:
  #          host: ${{ secrets.ARTIFACT_HOST }}
  #          username: ${{ secrets.ARTIFACT_USERNAME }}
  #          key: ${{ secrets.ARTIFACT_SSH_KEY }}
  #          source: "kloenk-client/html/assets/"
  #          target: "/usr/share/nginx/html/assets/"

  #          TODO just build and copy the files? why not? no need to use the registry really?
  #   TODO dont need secrets if that's true...
  #  maybe infra still needs though
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout project
#        uses: actions/checkout@v4.2.0
#
#      - name: Retrieve new container and run on server using remote ssh commands
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.ARTIFACT_HOST }}
#          username: ${{ secrets.ARTIFACT_USERNAME }}
#          key: ${{ secrets.ARTIFACT_SSH_KEY }}
#          script: docker pull hydrogax/kloenk-client && docker create --name kloenk-client hydrogax/kloenk-client && docker cp kloenk-client:/app/output/ /usr/share/nginx/html && docker cp kloenk-client:/app/output/ /usr/share/nginx/html/assets/
