name: deploy-web
run-name: Deploying web
on:
  push:
    branches: [ "main" ]
    paths: [ 'games/kloenk/kloenk-web/**', '.github/workflows/deploy-web.yaml' ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.0

      - name: Copy web pages to server using remote ssh commands
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.ARTIFACT_HOST }}
          username: ${{ secrets.ARTIFACT_USERNAME }}
          key: ${{ secrets.ARTIFACT_SSH_KEY }}
          source: "./games/kloenk/kloenk-web/html/index.html"
          target: "."

      - name: Move static files to shared docker volume
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ARTIFACT_HOST }}
          username: ${{ secrets.ARTIFACT_USERNAME }}
          key: ${{ secrets.ARTIFACT_SSH_KEY }}
          script: docker run --rm --mount type=bind,src=/home/deploy/games/kloenk/kloenk-web,dst=/source,readonly --mount type=volume,src=kloenk-static,dst=/target alpine cp -f /source/html/index.html /target/index.html
